replicaCount: 1

image:
  repository: linuxserver/heimdall
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  config:
    mountPath: /config
    hostPath: /var/lib/heimdall

env:
  TZ: Europe/Berlin

ports: 
  web:
    port: 80

ingress:
  local:
    host:
    subdomain: home.
    port: 80