
namespace: default

authURL:

replicaCount: 1

image:
  repository: authelia/authelia
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  config:
    mountPath: /config
    hostPath: /var/lib/authelia/config

ports: 
  auth:
    port: "9091"

env:
  TZ: Europe/Berlin

secretsFile:
  jwt_secret: 


ingress:
  local:
    host:
    subdomain: auth.
    port: 9091