apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseChart.name" . }}-deamon
  labels:
    app.kubernetes.io/name: {{ include "baseChart.name" . }}-deamon
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- /* Type of the service should be ClusterIP in mostcased so this is the default if no value is given */}}
  type: {{ .Values.deamon.service.type| default "ClusterIP" }}

  {{- /* Ports the service is exposing in the cluster */}}
  ports:
    - name: api
      port: {{ .Values.deamon.service.port }}
      targetPort: 4822
      protocol: TCP

  {{- /* Selectors to identify pods to forward to */}}
  selector:
    app.kubernetes.io/name: {{ include "baseChart.name" . }}-deamon
    app.kubernetes.io/instance: {{ .Release.Name }}