replicaCount: 1

image:
  repository: halverneus/static-file-server
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  static:
    mountPath: /web
    hostPath: /var/lib/files

env:
  DEBUG: false
  PORT: 8080

ports: 
  web:
    port: 8080

ingress:
  local:
    host:
    subdomain: files.
    port: 8080