{{- define "baseChart.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseChart.name" . }}{{ .Values.serviceSuffixInternal | default "" }}
  labels:
    {{- include "baseChart.labels" . | nindent 4 }}
spec:

  {{- if .Values.externalIP }}
  externalIPs: 
    - {{ .Values.externalIP }}
  {{- end }}

  {{- /* Type of the service should be ClusterIP in mostcased so this is the default if no value is given */}}
  type: {{ .Values.serviceType | default "ClusterIP" }}

  {{- /* Ports the service is exposing in the cluster */}}
  {{- if .Values.ports }}
  ports:
    {{- range $name, $value := .Values.ports }}
    - name: {{ $name }}
      port: {{ $value.port }}
      targetPort: {{ $value.target | default $value.port }}
      protocol: {{ $value.type | default "TCP" }}
    {{- end }}
  {{- end }}

  {{- /* Selectors to identify pods to forward to */}}
  selector:
    {{- include "baseChart.selectorLabels" . | nindent 4 }}

{{- end -}}