replicaCount: 1

image:
  repository: linuxserver/unifi-controller
  pullPolicy: IfNotPresent
  tag: ""

bind: 
  data:
    mountPath: /config
    hostPath: /var/lib/unifi

resources:
  limits:
    memory: 1G

# Internal ports
ports: 
  https:
    port: 8443

# Ingress
ingress:
  local:
    host: ""                           # Change this
    subdomain: unifi.
    port: 8443  