# Default values for homer.

replicaCount: 1

image:
  repository: vabene1111/recipes
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  static:
    mountPath: /opt/recipes/staticfiles
    hostPath: /var/lib/tandoor/static
  media:
    mountPath: /opt/recipes/mediafiles
    hostPath: /var/lib/tandoor/media

ports: 
  web:
    port: 8080

env:
  DB_ENGINE: django.db.backends.postgresql
  POSTGRES_DB: tandoor
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  # JS_REVERSE_SCRIPT_PREFIX: recipes  // enables subpath

env_secret:
  SECRET_KEY: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD:

ingress:
  local:
    host:
    subdomain: recipes.
    port: 8080